openapi: 3.1.0
info:
  version: 1.0.0
  title: Products application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation about Products app
tags:
  - name: Products
    description: Operations about Products
  - name: Auth
    description: Operations about authentication and authorization
servers:
  - url: http://localhost:3000
  - url: #посилання на задеплоєний сайт
paths:
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
